services:
  - type: web
    name: famsafe-app
    env: node
    plan: starter
    region: ohio
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
    disk:
      name: famsafe-data
      mountPath: /app/data
      sizeGB: 1
